"""Provider-agnostic web search abstraction, mirroring `llm_provider.py`.

`SearchProvider` is the seam between agent/service code and a concrete search
vendor. Client construction is lazy: constructing `TavilyProvider` never
requires an API key, only calling `search()` does.
"""

from __future__ import annotations

import typing
from abc import ABC, abstractmethod

from pydantic import BaseModel

from app.security.url_validation import is_valid_url
from app.tools.resilience import ResilienceConfig, with_retry

if typing.TYPE_CHECKING:
    from app.config.settings import Settings


class SearchResult(BaseModel):
    title: str
    url: str
    snippet: str
    source: str  # provider name, e.g. "tavily", "local"


class SearchProvider(ABC):
    name: str = "abstract"

    @abstractmethod
    async def search(self, query: str, max_results: int = 5) -> list[SearchResult]:
        raise NotImplementedError


class TavilyProvider(SearchProvider):
    name = "tavily"
    _API_URL = "https://api.tavily.com/search"

    def __init__(
        self,
        api_key: str | None,
        timeout_seconds: float = 30.0,
        resilience: ResilienceConfig | None = None,
    ) -> None:
        self._api_key = api_key
        self._timeout_seconds = timeout_seconds
        self._resilience = resilience or ResilienceConfig()
        self._breaker = self._resilience.new_breaker()

    async def search(self, query: str, max_results: int = 5) -> list[SearchResult]:
        if not self._api_key:
            raise RuntimeError(
                "TAVILY_API_KEY is not set; cannot use the tavily search provider."
            )
        import httpx

        async def _call() -> dict:
            async with httpx.AsyncClient(timeout=self._timeout_seconds) as client:
                response = await client.post(
                    self._API_URL,
                    json={
                        "api_key": self._api_key,
                        "query": query,
                        "max_results": max_results,
                    },
                )
                response.raise_for_status()
                return response.json()

        # Bounded retry/circuit breaker for timeout/rate-limit/provider-
        # unavailable (brief §26); "empty retrieval" on a call that does
        # succeed is handled by the caller (`app/agents/researcher.py`
        # already treats zero results as a non-fatal, continuable state).
        payload = await with_retry(
            _call,
            max_attempts=self._resilience.max_attempts,
            base_delay=self._resilience.base_delay,
            max_delay=self._resilience.max_delay,
            breaker=self._breaker,
        )

        results = []
        for item in payload.get("results", [])[:max_results]:
            url = item.get("url", "")
            # Phase 8 SSRF guard (brief §14/§27): a compromised/malicious
            # search result can't smuggle an internal/metadata-service URL
            # further into the pipeline -- drop it here rather than trusting
            # every URL a third-party search API returns.
            if url and not is_valid_url(url):
                continue
            results.append(
                SearchResult(
                    title=item.get("title", ""),
                    url=url,
                    snippet=item.get("content", ""),
                    source=self.name,
                )
            )
        return results


class LocalSearchProvider(SearchProvider):
    """Offline/dev/test fake: returns plausible canned results, no network call."""

    name = "local"

    async def search(self, query: str, max_results: int = 5) -> list[SearchResult]:
        results = []
        for i in range(max_results):
            results.append(
                SearchResult(
                    title=f"Local result {i + 1} for: {query}",
                    url=f"https://example.local/search?q={query.replace(' ', '+')}&r={i + 1}",
                    snippet=(
                        f"Canned offline snippet {i + 1} discussing '{query}'. "
                        "Generated by LocalSearchProvider for dev/test use — "
                        "not a real web result."
                    ),
                    source=self.name,
                )
            )
        return results


def get_search_provider(settings: Settings) -> SearchProvider:
    """Factory selecting the configured search provider."""
    if settings.search_provider == "tavily":
        return TavilyProvider(
            api_key=settings.tavily_api_key,
            timeout_seconds=settings.request_timeout_seconds,
            resilience=ResilienceConfig.from_settings(settings),
        )
    return LocalSearchProvider()
