"""phase8 users table

Revision ID: b7984e5fdb57
Revises: dee60aeb1011
Create Date: 2026-09-20 00:00:00.000000

Hand-written (not autogenerated), same style as the two prior migrations, to
mirror `app/models/orm.py`'s `UserORM` exactly (docs/database-schema.md
`users` table, Phase 8 auth: id/email/hashed_password/role/created_at).
`email` carries a unique index rather than a unique column constraint so the
migration matches the ORM's `Index(..., unique=True)` declaration exactly.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7984e5fdb57'
down_revision: Union[str, Sequence[str], None] = 'dee60aeb1011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'users',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
