"""phase4 risks assumptions decision_scores

Revision ID: dee60aeb1011
Revises: 7cf31237343d
Create Date: 2026-09-20 00:00:00.000000

Hand-written (not autogenerated) to mirror `app/models/orm.py`'s
`RiskORM`/`AssumptionORM`/`DecisionScoreORM` exactly, the same style as the
initial schema migration, following docs/database-schema.md's `risks`/
`assumptions`/`decision_scores` tables. `decision_scores.alternative_id`/
`criterion_id` are nullable (see `DecisionScoreORM`'s docstring: those rows
are resolved by name lookup against whatever `alternatives`/`criteria` rows
exist for the session's current plan, since agents never mint a stable id
for an alternative/criterion) and carry redundant `alternative_name`/
`criterion_name` columns so the row is still meaningful without the FK.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee60aeb1011'
down_revision: Union[str, Sequence[str], None] = '7cf31237343d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'risks',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.Uuid(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('probability', sa.String(), nullable=False),
        sa.Column('impact', sa.String(), nullable=False),
        sa.Column('severity', sa.Float(), nullable=False),
        sa.Column('mitigation', sa.Text(), nullable=False),
        sa.Column('evidence_ids', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_risks_session_id', 'risks', ['session_id'], unique=False)

    op.create_table(
        'assumptions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('session_id', sa.Uuid(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('origin', sa.String(), nullable=False),
        sa.Column('affects', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_assumptions_session_id', 'assumptions', ['session_id'], unique=False)

    op.create_table(
        'decision_scores',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('session_id', sa.Uuid(), nullable=False),
        sa.Column('alternative_id', sa.Uuid(), nullable=True),
        sa.Column('criterion_id', sa.Uuid(), nullable=True),
        sa.Column('alternative_name', sa.String(), nullable=False),
        sa.Column('criterion_name', sa.String(), nullable=False),
        sa.Column('score', sa.Float(), nullable=False),
        sa.Column('rationale', sa.Text(), nullable=False),
        sa.Column('evidence_ids', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['alternative_id'], ['alternatives.id'], ),
        sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
        sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_decision_scores_session_id', 'decision_scores', ['session_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_decision_scores_session_id', table_name='decision_scores')
    op.drop_table('decision_scores')
    op.drop_index('ix_assumptions_session_id', table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index('ix_risks_session_id', table_name='risks')
    op.drop_table('risks')
